[target.thumbv7em-none-eabihf]
# uncomment this to make `cargo run` execute programs on QEMU
runner = "qemu-system-arm -cpu cortex-m4 -machine b-l475e-iot01a -nographic -semihosting-config enable=on,target=native -kernel"

[build]
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)

